{
  "DFIntDebugFRMQualityLevelOverride": 1,
  "FIntRenderShadowIntensity": 0,
  "DFFlagTextureQualityOverrideEnabled": true,
  "DFIntTextureQualityOverride": 0,
  "FFlagDebugSkyGray": true,
  "FFlagNewLightAttenuation": "True",
  "FFlagFastGPULightCulling3": "True",
  "DFFlagDebugPauseVoxelizer": "True",
  "FIntRenderLocalLightFadeInMs": "0",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFIntTextureCompositorActiveJobs": "0",
  "FIntFRMMinGrassDistance": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntRenderGrassDetailStrands": "0",
  "FIntRenderGrassHeightScaler": "0",
  "FIntTerrainArraySliceSize": "0",
  "DFIntCSGLevelOfDetailSwitchingDistance": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL12": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL23": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL34": "0",
  "DFIntCSGv2LodsToGenerate": "0",
  "DFIntCSGv2LodMinTriangleCount": "0",
  "DFIntDebugRestrictGCDistance": "1"
}
